// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nettyrpc.proto

package com.googlecode.protobuf.netty;

public final class NettyRpcProto {
  private NettyRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BAD_REQUEST_DATA = 0;</code>
     *
     * <pre>
     * Server-side errors
     * </pre>
     */
    BAD_REQUEST_DATA(0, 0),
    /**
     * <code>BAD_REQUEST_PROTO = 1;</code>
     *
     * <pre>
     * Server received bad request proto
     * </pre>
     */
    BAD_REQUEST_PROTO(1, 1),
    /**
     * <code>SERVICE_NOT_FOUND = 2;</code>
     *
     * <pre>
     * Service not found on server
     * </pre>
     */
    SERVICE_NOT_FOUND(2, 2),
    /**
     * <code>METHOD_NOT_FOUND = 3;</code>
     *
     * <pre>
     * Method not found on server
     * </pre>
     */
    METHOD_NOT_FOUND(3, 3),
    /**
     * <code>RPC_ERROR = 4;</code>
     *
     * <pre>
     * Rpc threw exception on server
     * </pre>
     */
    RPC_ERROR(4, 4),
    /**
     * <code>RPC_FAILED = 5;</code>
     *
     * <pre>
     * Rpc failed on server
     * </pre>
     */
    RPC_FAILED(5, 5),
    /**
     * <code>INVALID_REQUEST_PROTO = 6;</code>
     *
     * <pre>
     * Client-side errors (these are returned by the client-side code)
     * </pre>
     */
    INVALID_REQUEST_PROTO(6, 6),
    /**
     * <code>BAD_RESPONSE_PROTO = 7;</code>
     *
     * <pre>
     * Server returned a bad response proto
     * </pre>
     */
    BAD_RESPONSE_PROTO(7, 7),
    /**
     * <code>UNKNOWN_HOST = 8;</code>
     *
     * <pre>
     * Could not find supplied host
     * </pre>
     */
    UNKNOWN_HOST(8, 8),
    /**
     * <code>IO_ERROR = 9;</code>
     *
     * <pre>
     * I/O error while communicating with server
     * </pre>
     */
    IO_ERROR(9, 9),
    ;

    /**
     * <code>BAD_REQUEST_DATA = 0;</code>
     *
     * <pre>
     * Server-side errors
     * </pre>
     */
    public static final int BAD_REQUEST_DATA_VALUE = 0;
    /**
     * <code>BAD_REQUEST_PROTO = 1;</code>
     *
     * <pre>
     * Server received bad request proto
     * </pre>
     */
    public static final int BAD_REQUEST_PROTO_VALUE = 1;
    /**
     * <code>SERVICE_NOT_FOUND = 2;</code>
     *
     * <pre>
     * Service not found on server
     * </pre>
     */
    public static final int SERVICE_NOT_FOUND_VALUE = 2;
    /**
     * <code>METHOD_NOT_FOUND = 3;</code>
     *
     * <pre>
     * Method not found on server
     * </pre>
     */
    public static final int METHOD_NOT_FOUND_VALUE = 3;
    /**
     * <code>RPC_ERROR = 4;</code>
     *
     * <pre>
     * Rpc threw exception on server
     * </pre>
     */
    public static final int RPC_ERROR_VALUE = 4;
    /**
     * <code>RPC_FAILED = 5;</code>
     *
     * <pre>
     * Rpc failed on server
     * </pre>
     */
    public static final int RPC_FAILED_VALUE = 5;
    /**
     * <code>INVALID_REQUEST_PROTO = 6;</code>
     *
     * <pre>
     * Client-side errors (these are returned by the client-side code)
     * </pre>
     */
    public static final int INVALID_REQUEST_PROTO_VALUE = 6;
    /**
     * <code>BAD_RESPONSE_PROTO = 7;</code>
     *
     * <pre>
     * Server returned a bad response proto
     * </pre>
     */
    public static final int BAD_RESPONSE_PROTO_VALUE = 7;
    /**
     * <code>UNKNOWN_HOST = 8;</code>
     *
     * <pre>
     * Could not find supplied host
     * </pre>
     */
    public static final int UNKNOWN_HOST_VALUE = 8;
    /**
     * <code>IO_ERROR = 9;</code>
     *
     * <pre>
     * I/O error while communicating with server
     * </pre>
     */
    public static final int IO_ERROR_VALUE = 9;


    public final int getNumber() { return value; }

    public static ErrorCode valueOf(int value) {
      switch (value) {
        case 0: return BAD_REQUEST_DATA;
        case 1: return BAD_REQUEST_PROTO;
        case 2: return SERVICE_NOT_FOUND;
        case 3: return METHOD_NOT_FOUND;
        case 4: return RPC_ERROR;
        case 5: return RPC_FAILED;
        case 6: return INVALID_REQUEST_PROTO;
        case 7: return BAD_RESPONSE_PROTO;
        case 8: return UNKNOWN_HOST;
        case 9: return IO_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.googlecode.protobuf.netty.NettyRpcProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrorCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ErrorCode)
  }

  public interface RpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * Sequence ID number, since Netty is asynchronious by nature
     * We need this to implement callbacks. This ID number is only
     * unique to a Netty Channel
     * NOTE: leave the ID out if you don't want any response
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * Sequence ID number, since Netty is asynchronious by nature
     * We need this to implement callbacks. This ID number is only
     * unique to a Netty Channel
     * NOTE: leave the ID out if you don't want any response
     * </pre>
     */
    int getId();

    /**
     * <code>required string service_name = 2;</code>
     */
    boolean hasServiceName();
    /**
     * <code>required string service_name = 2;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>required string service_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>required string method_name = 3;</code>
     */
    boolean hasMethodName();
    /**
     * <code>required string method_name = 3;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string method_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>required bool is_blocking_service = 4;</code>
     */
    boolean hasIsBlockingService();
    /**
     * <code>required bool is_blocking_service = 4;</code>
     */
    boolean getIsBlockingService();

    /**
     * <code>required bytes request_message = 5;</code>
     */
    boolean hasRequestMessage();
    /**
     * <code>required bytes request_message = 5;</code>
     */
    com.google.protobuf.ByteString getRequestMessage();
  }
  /**
   * Protobuf type {@code RpcRequest}
   */
  public static final class RpcRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RpcRequest)
      RpcRequestOrBuilder {
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcRequest defaultInstance;
    public static RpcRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RpcRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              serviceName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              methodName_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isBlockingService_ = input.readBool();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              requestMessage_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.netty.NettyRpcProto.internal_static_RpcRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.netty.NettyRpcProto.internal_static_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest.class, com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcRequest> PARSER =
        new com.google.protobuf.AbstractParser<RpcRequest>() {
      public RpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * Sequence ID number, since Netty is asynchronious by nature
     * We need this to implement callbacks. This ID number is only
     * unique to a Netty Channel
     * NOTE: leave the ID out if you don't want any response
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * Sequence ID number, since Netty is asynchronious by nature
     * We need this to implement callbacks. This ID number is only
     * unique to a Netty Channel
     * NOTE: leave the ID out if you don't want any response
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int SERVICE_NAME_FIELD_NUMBER = 2;
    private java.lang.Object serviceName_;
    /**
     * <code>required string service_name = 2;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string service_name = 2;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string service_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 3;
    private java.lang.Object methodName_;
    /**
     * <code>required string method_name = 3;</code>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string method_name = 3;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string method_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_BLOCKING_SERVICE_FIELD_NUMBER = 4;
    private boolean isBlockingService_;
    /**
     * <code>required bool is_blocking_service = 4;</code>
     */
    public boolean hasIsBlockingService() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool is_blocking_service = 4;</code>
     */
    public boolean getIsBlockingService() {
      return isBlockingService_;
    }

    public static final int REQUEST_MESSAGE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString requestMessage_;
    /**
     * <code>required bytes request_message = 5;</code>
     */
    public boolean hasRequestMessage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes request_message = 5;</code>
     */
    public com.google.protobuf.ByteString getRequestMessage() {
      return requestMessage_;
    }

    private void initFields() {
      id_ = 0;
      serviceName_ = "";
      methodName_ = "";
      isBlockingService_ = false;
      requestMessage_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServiceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsBlockingService()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isBlockingService_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, requestMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isBlockingService_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, requestMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RpcRequest)
        com.googlecode.protobuf.netty.NettyRpcProto.RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.googlecode.protobuf.netty.NettyRpcProto.internal_static_RpcRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.googlecode.protobuf.netty.NettyRpcProto.internal_static_RpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest.class, com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest.Builder.class);
      }

      // Construct using com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        isBlockingService_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        requestMessage_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.netty.NettyRpcProto.internal_static_RpcRequest_descriptor;
      }

      public com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest getDefaultInstanceForType() {
        return com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest.getDefaultInstance();
      }

      public com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest build() {
        com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest buildPartial() {
        com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest result = new com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isBlockingService_ = isBlockingService_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.requestMessage_ = requestMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest) {
          return mergeFrom((com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest other) {
        if (other == com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000002;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000004;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasIsBlockingService()) {
          setIsBlockingService(other.getIsBlockingService());
        }
        if (other.hasRequestMessage()) {
          setRequestMessage(other.getRequestMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServiceName()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        if (!hasIsBlockingService()) {
          
          return false;
        }
        if (!hasRequestMessage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.googlecode.protobuf.netty.NettyRpcProto.RpcRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       * Sequence ID number, since Netty is asynchronious by nature
       * We need this to implement callbacks. This ID number is only
       * unique to a Netty Channel
       * NOTE: leave the ID out if you don't want any response
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       * Sequence ID number, since Netty is asynchronious by nature
       * We need this to implement callbacks. This ID number is only
       * unique to a Netty Channel
       * NOTE: leave the ID out if you don't want any response
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       * Sequence ID number, since Netty is asynchronious by nature
       * We need this to implement callbacks. This ID number is only
       * unique to a Netty Channel
       * NOTE: leave the ID out if you don't want any response
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       * Sequence ID number, since Netty is asynchronious by nature
       * We need this to implement callbacks. This ID number is only
       * unique to a Netty Channel
       * NOTE: leave the ID out if you don't want any response
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object serviceName_ = "";
      /**
       * <code>required string service_name = 2;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string service_name = 2;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string service_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string service_name = 2;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string service_name = 2;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string service_name = 2;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>required string method_name = 3;</code>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string method_name = 3;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            methodName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string method_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string method_name = 3;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string method_name = 3;</code>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>required string method_name = 3;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        methodName_ = value;
        onChanged();
        return this;
      }

      private boolean isBlockingService_ ;
      /**
       * <code>required bool is_blocking_service = 4;</code>
       */
      public boolean hasIsBlockingService() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool is_blocking_service = 4;</code>
       */
      public boolean getIsBlockingService() {
        return isBlockingService_;
      }
      /**
       * <code>required bool is_blocking_service = 4;</code>
       */
      public Builder setIsBlockingService(boolean value) {
        bitField0_ |= 0x00000008;
        isBlockingService_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool is_blocking_service = 4;</code>
       */
      public Builder clearIsBlockingService() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isBlockingService_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString requestMessage_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes request_message = 5;</code>
       */
      public boolean hasRequestMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes request_message = 5;</code>
       */
      public com.google.protobuf.ByteString getRequestMessage() {
        return requestMessage_;
      }
      /**
       * <code>required bytes request_message = 5;</code>
       */
      public Builder setRequestMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        requestMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes request_message = 5;</code>
       */
      public Builder clearRequestMessage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        requestMessage_ = getDefaultInstance().getRequestMessage();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RpcRequest)
    }

    static {
      defaultInstance = new RpcRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RpcRequest)
  }

  public interface RpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RpcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * Request Sequence ID number that this response is
     * "responding" to. This is *required* since we don't
     * send back responses unless a sequence ID was provided
     * (that would be extra traffic not necessary)
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * Request Sequence ID number that this response is
     * "responding" to. This is *required* since we don't
     * send back responses unless a sequence ID was provided
     * (that would be extra traffic not necessary)
     * </pre>
     */
    int getId();

    /**
     * <code>optional bytes response_message = 2;</code>
     *
     * <pre>
     * This is optional, since we could be sending back an
     * error response in which case we would not have a
     * response message
     * </pre>
     */
    boolean hasResponseMessage();
    /**
     * <code>optional bytes response_message = 2;</code>
     *
     * <pre>
     * This is optional, since we could be sending back an
     * error response in which case we would not have a
     * response message
     * </pre>
     */
    com.google.protobuf.ByteString getResponseMessage();

    /**
     * <code>optional .ErrorCode error_code = 3;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional .ErrorCode error_code = 3;</code>
     */
    com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode getErrorCode();

    /**
     * <code>optional string error_message = 4;</code>
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string error_message = 4;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string error_message = 4;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code RpcResponse}
   */
  public static final class RpcResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RpcResponse)
      RpcResponseOrBuilder {
    // Use RpcResponse.newBuilder() to construct.
    private RpcResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcResponse defaultInstance;
    public static RpcResponse getDefaultInstance() {
      return defaultInstance;
    }

    public RpcResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              responseMessage_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode value = com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                errorCode_ = value;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              errorMessage_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.netty.NettyRpcProto.internal_static_RpcResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.netty.NettyRpcProto.internal_static_RpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse.class, com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcResponse> PARSER =
        new com.google.protobuf.AbstractParser<RpcResponse>() {
      public RpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * Request Sequence ID number that this response is
     * "responding" to. This is *required* since we don't
     * send back responses unless a sequence ID was provided
     * (that would be extra traffic not necessary)
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * Request Sequence ID number that this response is
     * "responding" to. This is *required* since we don't
     * send back responses unless a sequence ID was provided
     * (that would be extra traffic not necessary)
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int RESPONSE_MESSAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString responseMessage_;
    /**
     * <code>optional bytes response_message = 2;</code>
     *
     * <pre>
     * This is optional, since we could be sending back an
     * error response in which case we would not have a
     * response message
     * </pre>
     */
    public boolean hasResponseMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes response_message = 2;</code>
     *
     * <pre>
     * This is optional, since we could be sending back an
     * error response in which case we would not have a
     * response message
     * </pre>
     */
    public com.google.protobuf.ByteString getResponseMessage() {
      return responseMessage_;
    }

    public static final int ERROR_CODE_FIELD_NUMBER = 3;
    private com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode errorCode_;
    /**
     * <code>optional .ErrorCode error_code = 3;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .ErrorCode error_code = 3;</code>
     */
    public com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode getErrorCode() {
      return errorCode_;
    }

    public static final int ERROR_MESSAGE_FIELD_NUMBER = 4;
    private java.lang.Object errorMessage_;
    /**
     * <code>optional string error_message = 4;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string error_message = 4;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error_message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      responseMessage_ = com.google.protobuf.ByteString.EMPTY;
      errorCode_ = com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode.BAD_REQUEST_DATA;
      errorMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, responseMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, errorCode_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getErrorMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, responseMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, errorCode_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getErrorMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RpcResponse)
        com.googlecode.protobuf.netty.NettyRpcProto.RpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.googlecode.protobuf.netty.NettyRpcProto.internal_static_RpcResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.googlecode.protobuf.netty.NettyRpcProto.internal_static_RpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse.class, com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse.Builder.class);
      }

      // Construct using com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseMessage_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode.BAD_REQUEST_DATA;
        bitField0_ = (bitField0_ & ~0x00000004);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.netty.NettyRpcProto.internal_static_RpcResponse_descriptor;
      }

      public com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse getDefaultInstanceForType() {
        return com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse.getDefaultInstance();
      }

      public com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse build() {
        com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse buildPartial() {
        com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse result = new com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseMessage_ = responseMessage_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.errorMessage_ = errorMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse) {
          return mergeFrom((com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse other) {
        if (other == com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasResponseMessage()) {
          setResponseMessage(other.getResponseMessage());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000008;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.googlecode.protobuf.netty.NettyRpcProto.RpcResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * Request Sequence ID number that this response is
       * "responding" to. This is *required* since we don't
       * send back responses unless a sequence ID was provided
       * (that would be extra traffic not necessary)
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * Request Sequence ID number that this response is
       * "responding" to. This is *required* since we don't
       * send back responses unless a sequence ID was provided
       * (that would be extra traffic not necessary)
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * Request Sequence ID number that this response is
       * "responding" to. This is *required* since we don't
       * send back responses unless a sequence ID was provided
       * (that would be extra traffic not necessary)
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * Request Sequence ID number that this response is
       * "responding" to. This is *required* since we don't
       * send back responses unless a sequence ID was provided
       * (that would be extra traffic not necessary)
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString responseMessage_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response_message = 2;</code>
       *
       * <pre>
       * This is optional, since we could be sending back an
       * error response in which case we would not have a
       * response message
       * </pre>
       */
      public boolean hasResponseMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes response_message = 2;</code>
       *
       * <pre>
       * This is optional, since we could be sending back an
       * error response in which case we would not have a
       * response message
       * </pre>
       */
      public com.google.protobuf.ByteString getResponseMessage() {
        return responseMessage_;
      }
      /**
       * <code>optional bytes response_message = 2;</code>
       *
       * <pre>
       * This is optional, since we could be sending back an
       * error response in which case we would not have a
       * response message
       * </pre>
       */
      public Builder setResponseMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response_message = 2;</code>
       *
       * <pre>
       * This is optional, since we could be sending back an
       * error response in which case we would not have a
       * response message
       * </pre>
       */
      public Builder clearResponseMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }

      private com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode errorCode_ = com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode.BAD_REQUEST_DATA;
      /**
       * <code>optional .ErrorCode error_code = 3;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .ErrorCode error_code = 3;</code>
       */
      public com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional .ErrorCode error_code = 3;</code>
       */
      public Builder setErrorCode(com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ErrorCode error_code = 3;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorCode_ = com.googlecode.protobuf.netty.NettyRpcProto.ErrorCode.BAD_REQUEST_DATA;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string error_message = 4;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string error_message = 4;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error_message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error_message = 4;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_message = 4;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_message = 4;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorMessage_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RpcResponse)
    }

    static {
      defaultInstance = new RpcResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RpcResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016nettyrpc.proto\"y\n\nRpcRequest\022\n\n\002id\030\001 \001" +
      "(\005\022\024\n\014service_name\030\002 \002(\t\022\023\n\013method_name\030" +
      "\003 \002(\t\022\033\n\023is_blocking_service\030\004 \002(\010\022\027\n\017re" +
      "quest_message\030\005 \002(\014\"j\n\013RpcResponse\022\n\n\002id" +
      "\030\001 \002(\005\022\030\n\020response_message\030\002 \001(\014\022\036\n\nerro" +
      "r_code\030\003 \001(\0162\n.ErrorCode\022\025\n\rerror_messag" +
      "e\030\004 \001(\t*\327\001\n\tErrorCode\022\024\n\020BAD_REQUEST_DAT" +
      "A\020\000\022\025\n\021BAD_REQUEST_PROTO\020\001\022\025\n\021SERVICE_NO" +
      "T_FOUND\020\002\022\024\n\020METHOD_NOT_FOUND\020\003\022\r\n\tRPC_E" +
      "RROR\020\004\022\016\n\nRPC_FAILED\020\005\022\031\n\025INVALID_REQUES",
      "T_PROTO\020\006\022\026\n\022BAD_RESPONSE_PROTO\020\007\022\020\n\014UNK" +
      "NOWN_HOST\020\010\022\014\n\010IO_ERROR\020\tB0\n\035com.googlec" +
      "ode.protobuf.nettyB\rNettyRpcProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RpcRequest_descriptor,
        new java.lang.String[] { "Id", "ServiceName", "MethodName", "IsBlockingService", "RequestMessage", });
    internal_static_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RpcResponse_descriptor,
        new java.lang.String[] { "Id", "ResponseMessage", "ErrorCode", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
