// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.yobennett.calculator;

public final class Calculator {
  private Calculator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CalculatorRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CalculatorRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 op1 = 1;</code>
     */
    boolean hasOp1();
    /**
     * <code>required int32 op1 = 1;</code>
     */
    int getOp1();

    /**
     * <code>required int32 op2 = 2;</code>
     */
    boolean hasOp2();
    /**
     * <code>required int32 op2 = 2;</code>
     */
    int getOp2();
  }
  /**
   * Protobuf type {@code CalculatorRequest}
   */
  public static final class CalculatorRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CalculatorRequest)
      CalculatorRequestOrBuilder {
    // Use CalculatorRequest.newBuilder() to construct.
    private CalculatorRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalculatorRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalculatorRequest defaultInstance;
    public static CalculatorRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CalculatorRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalculatorRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              op1_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              op2_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yobennett.calculator.Calculator.internal_static_CalculatorRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yobennett.calculator.Calculator.internal_static_CalculatorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yobennett.calculator.Calculator.CalculatorRequest.class, com.yobennett.calculator.Calculator.CalculatorRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CalculatorRequest> PARSER =
        new com.google.protobuf.AbstractParser<CalculatorRequest>() {
      public CalculatorRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalculatorRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalculatorRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OP1_FIELD_NUMBER = 1;
    private int op1_;
    /**
     * <code>required int32 op1 = 1;</code>
     */
    public boolean hasOp1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 op1 = 1;</code>
     */
    public int getOp1() {
      return op1_;
    }

    public static final int OP2_FIELD_NUMBER = 2;
    private int op2_;
    /**
     * <code>required int32 op2 = 2;</code>
     */
    public boolean hasOp2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 op2 = 2;</code>
     */
    public int getOp2() {
      return op2_;
    }

    private void initFields() {
      op1_ = 0;
      op2_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOp1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOp2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, op1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, op2_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, op1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, op2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yobennett.calculator.Calculator.CalculatorRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yobennett.calculator.Calculator.CalculatorRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yobennett.calculator.Calculator.CalculatorRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yobennett.calculator.Calculator.CalculatorRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yobennett.calculator.Calculator.CalculatorRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yobennett.calculator.Calculator.CalculatorRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yobennett.calculator.Calculator.CalculatorRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yobennett.calculator.Calculator.CalculatorRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yobennett.calculator.Calculator.CalculatorRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yobennett.calculator.Calculator.CalculatorRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yobennett.calculator.Calculator.CalculatorRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalculatorRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CalculatorRequest)
        com.yobennett.calculator.Calculator.CalculatorRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yobennett.calculator.Calculator.internal_static_CalculatorRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yobennett.calculator.Calculator.internal_static_CalculatorRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yobennett.calculator.Calculator.CalculatorRequest.class, com.yobennett.calculator.Calculator.CalculatorRequest.Builder.class);
      }

      // Construct using com.yobennett.calculator.Calculator.CalculatorRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        op1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        op2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yobennett.calculator.Calculator.internal_static_CalculatorRequest_descriptor;
      }

      public com.yobennett.calculator.Calculator.CalculatorRequest getDefaultInstanceForType() {
        return com.yobennett.calculator.Calculator.CalculatorRequest.getDefaultInstance();
      }

      public com.yobennett.calculator.Calculator.CalculatorRequest build() {
        com.yobennett.calculator.Calculator.CalculatorRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yobennett.calculator.Calculator.CalculatorRequest buildPartial() {
        com.yobennett.calculator.Calculator.CalculatorRequest result = new com.yobennett.calculator.Calculator.CalculatorRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.op1_ = op1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.op2_ = op2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yobennett.calculator.Calculator.CalculatorRequest) {
          return mergeFrom((com.yobennett.calculator.Calculator.CalculatorRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yobennett.calculator.Calculator.CalculatorRequest other) {
        if (other == com.yobennett.calculator.Calculator.CalculatorRequest.getDefaultInstance()) return this;
        if (other.hasOp1()) {
          setOp1(other.getOp1());
        }
        if (other.hasOp2()) {
          setOp2(other.getOp2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOp1()) {
          
          return false;
        }
        if (!hasOp2()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yobennett.calculator.Calculator.CalculatorRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yobennett.calculator.Calculator.CalculatorRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int op1_ ;
      /**
       * <code>required int32 op1 = 1;</code>
       */
      public boolean hasOp1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 op1 = 1;</code>
       */
      public int getOp1() {
        return op1_;
      }
      /**
       * <code>required int32 op1 = 1;</code>
       */
      public Builder setOp1(int value) {
        bitField0_ |= 0x00000001;
        op1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 op1 = 1;</code>
       */
      public Builder clearOp1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        op1_ = 0;
        onChanged();
        return this;
      }

      private int op2_ ;
      /**
       * <code>required int32 op2 = 2;</code>
       */
      public boolean hasOp2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 op2 = 2;</code>
       */
      public int getOp2() {
        return op2_;
      }
      /**
       * <code>required int32 op2 = 2;</code>
       */
      public Builder setOp2(int value) {
        bitField0_ |= 0x00000002;
        op2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 op2 = 2;</code>
       */
      public Builder clearOp2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        op2_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CalculatorRequest)
    }

    static {
      defaultInstance = new CalculatorRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CalculatorRequest)
  }

  public interface CalculatorResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CalculatorResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required int32 result = 1;</code>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code CalculatorResponse}
   */
  public static final class CalculatorResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CalculatorResponse)
      CalculatorResponseOrBuilder {
    // Use CalculatorResponse.newBuilder() to construct.
    private CalculatorResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalculatorResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalculatorResponse defaultInstance;
    public static CalculatorResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CalculatorResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalculatorResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yobennett.calculator.Calculator.internal_static_CalculatorResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yobennett.calculator.Calculator.internal_static_CalculatorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yobennett.calculator.Calculator.CalculatorResponse.class, com.yobennett.calculator.Calculator.CalculatorResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CalculatorResponse> PARSER =
        new com.google.protobuf.AbstractParser<CalculatorResponse>() {
      public CalculatorResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalculatorResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalculatorResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required int32 result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yobennett.calculator.Calculator.CalculatorResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yobennett.calculator.Calculator.CalculatorResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yobennett.calculator.Calculator.CalculatorResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yobennett.calculator.Calculator.CalculatorResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yobennett.calculator.Calculator.CalculatorResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yobennett.calculator.Calculator.CalculatorResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yobennett.calculator.Calculator.CalculatorResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yobennett.calculator.Calculator.CalculatorResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yobennett.calculator.Calculator.CalculatorResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yobennett.calculator.Calculator.CalculatorResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yobennett.calculator.Calculator.CalculatorResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalculatorResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CalculatorResponse)
        com.yobennett.calculator.Calculator.CalculatorResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yobennett.calculator.Calculator.internal_static_CalculatorResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yobennett.calculator.Calculator.internal_static_CalculatorResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yobennett.calculator.Calculator.CalculatorResponse.class, com.yobennett.calculator.Calculator.CalculatorResponse.Builder.class);
      }

      // Construct using com.yobennett.calculator.Calculator.CalculatorResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yobennett.calculator.Calculator.internal_static_CalculatorResponse_descriptor;
      }

      public com.yobennett.calculator.Calculator.CalculatorResponse getDefaultInstanceForType() {
        return com.yobennett.calculator.Calculator.CalculatorResponse.getDefaultInstance();
      }

      public com.yobennett.calculator.Calculator.CalculatorResponse build() {
        com.yobennett.calculator.Calculator.CalculatorResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yobennett.calculator.Calculator.CalculatorResponse buildPartial() {
        com.yobennett.calculator.Calculator.CalculatorResponse result = new com.yobennett.calculator.Calculator.CalculatorResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yobennett.calculator.Calculator.CalculatorResponse) {
          return mergeFrom((com.yobennett.calculator.Calculator.CalculatorResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yobennett.calculator.Calculator.CalculatorResponse other) {
        if (other == com.yobennett.calculator.Calculator.CalculatorResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yobennett.calculator.Calculator.CalculatorResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yobennett.calculator.Calculator.CalculatorResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>required int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CalculatorResponse)
    }

    static {
      defaultInstance = new CalculatorResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CalculatorResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculatorRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CalculatorRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculatorResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CalculatorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020calculator.proto\"-\n\021CalculatorRequest\022" +
      "\013\n\003op1\030\001 \002(\005\022\013\n\003op2\030\002 \002(\005\"$\n\022CalculatorR" +
      "esponse\022\016\n\006result\030\001 \002(\0052\340\001\n\021CalculatorSe" +
      "rvice\022.\n\003Add\022\022.CalculatorRequest\032\023.Calcu" +
      "latorResponse\0223\n\010Subtract\022\022.CalculatorRe" +
      "quest\032\023.CalculatorResponse\0223\n\010Multiply\022\022" +
      ".CalculatorRequest\032\023.CalculatorResponse\022" +
      "1\n\006Divide\022\022.CalculatorRequest\032\023.Calculat" +
      "orResponseB&\n\030com.yobennett.calculatorB\n" +
      "Calculator"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CalculatorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CalculatorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CalculatorRequest_descriptor,
        new java.lang.String[] { "Op1", "Op2", });
    internal_static_CalculatorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CalculatorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CalculatorResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
