// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: whoami.proto

package com.yobennett.whoami;

public final class WhoAmI {
  private WhoAmI() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WhoamiRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:whoami.WhoamiRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code whoami.WhoamiRequest}
   */
  public static final class WhoamiRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:whoami.WhoamiRequest)
      WhoamiRequestOrBuilder {
    // Use WhoamiRequest.newBuilder() to construct.
    private WhoamiRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WhoamiRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WhoamiRequest defaultInstance;
    public static WhoamiRequest getDefaultInstance() {
      return defaultInstance;
    }

    public WhoamiRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WhoamiRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yobennett.whoami.WhoAmI.internal_static_whoami_WhoamiRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yobennett.whoami.WhoAmI.internal_static_whoami_WhoamiRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yobennett.whoami.WhoAmI.WhoamiRequest.class, com.yobennett.whoami.WhoAmI.WhoamiRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<WhoamiRequest> PARSER =
        new com.google.protobuf.AbstractParser<WhoamiRequest>() {
      public WhoamiRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WhoamiRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WhoamiRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yobennett.whoami.WhoAmI.WhoamiRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yobennett.whoami.WhoAmI.WhoamiRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code whoami.WhoamiRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:whoami.WhoamiRequest)
        com.yobennett.whoami.WhoAmI.WhoamiRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yobennett.whoami.WhoAmI.internal_static_whoami_WhoamiRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yobennett.whoami.WhoAmI.internal_static_whoami_WhoamiRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yobennett.whoami.WhoAmI.WhoamiRequest.class, com.yobennett.whoami.WhoAmI.WhoamiRequest.Builder.class);
      }

      // Construct using com.yobennett.whoami.WhoAmI.WhoamiRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yobennett.whoami.WhoAmI.internal_static_whoami_WhoamiRequest_descriptor;
      }

      public com.yobennett.whoami.WhoAmI.WhoamiRequest getDefaultInstanceForType() {
        return com.yobennett.whoami.WhoAmI.WhoamiRequest.getDefaultInstance();
      }

      public com.yobennett.whoami.WhoAmI.WhoamiRequest build() {
        com.yobennett.whoami.WhoAmI.WhoamiRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yobennett.whoami.WhoAmI.WhoamiRequest buildPartial() {
        com.yobennett.whoami.WhoAmI.WhoamiRequest result = new com.yobennett.whoami.WhoAmI.WhoamiRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yobennett.whoami.WhoAmI.WhoamiRequest) {
          return mergeFrom((com.yobennett.whoami.WhoAmI.WhoamiRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yobennett.whoami.WhoAmI.WhoamiRequest other) {
        if (other == com.yobennett.whoami.WhoAmI.WhoamiRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yobennett.whoami.WhoAmI.WhoamiRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yobennett.whoami.WhoAmI.WhoamiRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:whoami.WhoamiRequest)
    }

    static {
      defaultInstance = new WhoamiRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:whoami.WhoamiRequest)
  }

  public interface WhoamiResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:whoami.WhoamiResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ip_addr = 1;</code>
     */
    boolean hasIpAddr();
    /**
     * <code>required string ip_addr = 1;</code>
     */
    java.lang.String getIpAddr();
    /**
     * <code>required string ip_addr = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpAddrBytes();
  }
  /**
   * Protobuf type {@code whoami.WhoamiResponse}
   */
  public static final class WhoamiResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:whoami.WhoamiResponse)
      WhoamiResponseOrBuilder {
    // Use WhoamiResponse.newBuilder() to construct.
    private WhoamiResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WhoamiResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WhoamiResponse defaultInstance;
    public static WhoamiResponse getDefaultInstance() {
      return defaultInstance;
    }

    public WhoamiResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WhoamiResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              ipAddr_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yobennett.whoami.WhoAmI.internal_static_whoami_WhoamiResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yobennett.whoami.WhoAmI.internal_static_whoami_WhoamiResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yobennett.whoami.WhoAmI.WhoamiResponse.class, com.yobennett.whoami.WhoAmI.WhoamiResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<WhoamiResponse> PARSER =
        new com.google.protobuf.AbstractParser<WhoamiResponse>() {
      public WhoamiResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WhoamiResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WhoamiResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IP_ADDR_FIELD_NUMBER = 1;
    private java.lang.Object ipAddr_;
    /**
     * <code>required string ip_addr = 1;</code>
     */
    public boolean hasIpAddr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ip_addr = 1;</code>
     */
    public java.lang.String getIpAddr() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipAddr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip_addr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddrBytes() {
      java.lang.Object ref = ipAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ipAddr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIpAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIpAddrBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIpAddrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yobennett.whoami.WhoAmI.WhoamiResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yobennett.whoami.WhoAmI.WhoamiResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yobennett.whoami.WhoAmI.WhoamiResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code whoami.WhoamiResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:whoami.WhoamiResponse)
        com.yobennett.whoami.WhoAmI.WhoamiResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yobennett.whoami.WhoAmI.internal_static_whoami_WhoamiResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yobennett.whoami.WhoAmI.internal_static_whoami_WhoamiResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yobennett.whoami.WhoAmI.WhoamiResponse.class, com.yobennett.whoami.WhoAmI.WhoamiResponse.Builder.class);
      }

      // Construct using com.yobennett.whoami.WhoAmI.WhoamiResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ipAddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yobennett.whoami.WhoAmI.internal_static_whoami_WhoamiResponse_descriptor;
      }

      public com.yobennett.whoami.WhoAmI.WhoamiResponse getDefaultInstanceForType() {
        return com.yobennett.whoami.WhoAmI.WhoamiResponse.getDefaultInstance();
      }

      public com.yobennett.whoami.WhoAmI.WhoamiResponse build() {
        com.yobennett.whoami.WhoAmI.WhoamiResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yobennett.whoami.WhoAmI.WhoamiResponse buildPartial() {
        com.yobennett.whoami.WhoAmI.WhoamiResponse result = new com.yobennett.whoami.WhoAmI.WhoamiResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ipAddr_ = ipAddr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yobennett.whoami.WhoAmI.WhoamiResponse) {
          return mergeFrom((com.yobennett.whoami.WhoAmI.WhoamiResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yobennett.whoami.WhoAmI.WhoamiResponse other) {
        if (other == com.yobennett.whoami.WhoAmI.WhoamiResponse.getDefaultInstance()) return this;
        if (other.hasIpAddr()) {
          bitField0_ |= 0x00000001;
          ipAddr_ = other.ipAddr_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIpAddr()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yobennett.whoami.WhoAmI.WhoamiResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yobennett.whoami.WhoAmI.WhoamiResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object ipAddr_ = "";
      /**
       * <code>required string ip_addr = 1;</code>
       */
      public boolean hasIpAddr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ip_addr = 1;</code>
       */
      public java.lang.String getIpAddr() {
        java.lang.Object ref = ipAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipAddr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip_addr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddrBytes() {
        java.lang.Object ref = ipAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip_addr = 1;</code>
       */
      public Builder setIpAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ipAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip_addr = 1;</code>
       */
      public Builder clearIpAddr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ipAddr_ = getDefaultInstance().getIpAddr();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip_addr = 1;</code>
       */
      public Builder setIpAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ipAddr_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:whoami.WhoamiResponse)
    }

    static {
      defaultInstance = new WhoamiResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:whoami.WhoamiResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_whoami_WhoamiRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_whoami_WhoamiRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_whoami_WhoamiResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_whoami_WhoamiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014whoami.proto\022\006whoami\"\017\n\rWhoamiRequest\"" +
      "!\n\016WhoamiResponse\022\017\n\007ip_addr\030\001 \002(\t2H\n\rWh" +
      "oamiService\0227\n\006Whoami\022\025.whoami.WhoamiReq" +
      "uest\032\026.whoami.WhoamiResponseB\036\n\024com.yobe" +
      "nnett.whoamiB\006WhoAmI"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_whoami_WhoamiRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_whoami_WhoamiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_whoami_WhoamiRequest_descriptor,
        new java.lang.String[] { });
    internal_static_whoami_WhoamiResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_whoami_WhoamiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_whoami_WhoamiResponse_descriptor,
        new java.lang.String[] { "IpAddr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
